# Generated by Django 2.1.3 on 2018-12-10 04:31

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181210_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='par',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
